### ISSUE TITLE
ValueError: could not convert string to float: '[Not Supported]'

### ISSUE THREAD

**Issue by artBoffin** [albarji/neural-style-docker#26]
> Traceback (most recent call last):
  File "/app/entrypoint/entrypoint.py", line 100, in main
    styletransfer(contents, styles, savefolder, size, alg, weights, stylescales, tileoverlap, algparams=otherparams)
  File "/app/entrypoint/neuralstyle/algorithms.py", line 84, in styletransfer
    if fitsingletile(targetshape(content, size), alg):
  File "/app/entrypoint/neuralstyle/algorithms.py", line 336, in fitsingletile
    mx = maxtile(alg)
  File "/app/entrypoint/neuralstyle/algorithms.py", line 366, in maxtile
    gname = gpuname()
  File "/app/entrypoint/neuralstyle/algorithms.py", line 354, in gpuname
    gpus = GPUtil.getGPUs()
  File "/opt/miniconda/lib/python3.6/site-packages/GPUtil/__init__.py", line 82, in getGPUs
    gpuUtil[g] = float(vals[i])/100
ValueError: could not convert string to float: '[Not Supported]'

**Comment by kuriot** [comment]
Hello.

I have the same issue. All dependencies are installed and other containers show output of nvidia-smi. I try to simply run it with an example run line, of course changing filenames to mine.

```
nvidia-docker run --rm -v $(pwd):/images albarji/neural-style --content somecontent.png --style somestyle.png
```

**Comment by albarji** [comment]
Thanks for reporting this. This seems to be related with a failure to detect the GPU model in your system. I will add a patch that assumes default rendering parameters when this check fails.

**Comment by albarji** [comment]
I have updated the image for this project in Docker hub. Could you please try again and report what you obtain? I have only been able to reproduce this bug when nvidia-docker was not properly configured. Also make sure you driver version supports CUDA 8.0 or higher.
